version: '3.8'

# Services
services:

  # NGINX Service
  nginx-web-chat:
    image: nginx:latest
    container_name: nginx-web-chat
    restart: always
    ports:
      - 80:80
      - 8000:80
    volumes:
      - ./:/var/www/web-chat.loc
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-web-chat
    networks:
      - network-web-chat

  # PHP Service
  php-web-chat:
    image: php-web-chat
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    working_dir: /var/www/web-chat.loc
    container_name: php-web-chat
    volumes:
      - ./:/var/www/web-chat.loc
      - /var/www/web-chat.loc/vendor
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      mysql-web-chat:
        condition: service_healthy
    networks:
      - network-web-chat

  # WebSocket service
  ws-web-chat:
    image: ws-web-chat
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    container_name: ws-web-chat
    volumes:
      - ./:/var/www/web-chat.loc
      - /var/www/web-chat.loc/vendor
    depends_on:
      mysql-web-chat:
        condition: service_healthy
    entrypoint: ["php", "/var/www/web-chat.loc/websocket.php", "start"]
    expose: 
      - 8282
    networks:
      - network-web-chat

  # MySQL Service
  mysql-web-chat:
    image: mysql:latest
    restart: always
    container_name: mysql-web-chat
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+03:00']
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
    networks:
      network-web-chat:
        aliases:
          - ${MYSQL_HOST_ALIAS}

  # PhpMyAdmin Service
  phpmyadmin-web-chat:
    image: phpmyadmin
    container_name: pma-web-chat
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      mysql-web-chat:
        condition: service_healthy
    networks:
      - network-web-chat

# Volumes
volumes:
  mysqldata:

# Networks
networks:
  network-web-chat:
    name: network-web-chat
    driver: bridge